<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Device extends Model
{
    public function branches(){
        return $this->belongsTo(Branch::class,'branch_id');
    }

    public function device_templates(){
        return $this->hasMany(DeviceTemplates::class);
    }
    public function schedule_templates(){
        return $this->hasMany(ScheduleTemplates::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($device){
            $device->device_templates()->delete();
        });
    }

    public function device_group()
    {
        return $this->belongsTo(DeviceGroup::class,'device_group_id');
    }
}
